[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossbeam = "0.8.4"
fern = "0.7.1"
log = "0.4.28"
rayon = "1.11.0"
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
warp = "0.4.2"
